# This is a basic workflow to help you get started with Actions

name: Deploy
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm run build
        env:
          CI: false
      #- run: echo feedeck.sibr.dev > build/CNAME
      - run: git --work-tree build add --all
      - run: git -c user.name=jmaliksi commit -m "Automatic deploy"
      - run: git push origin HEAD:gh-pages --force
